### ISSUE TITLE
GUI fails to start if pyqtgraph>0.12.2

### ISSUE THREAD

**Issue by aywlin** [ercius/4dcamera_gui#4]
**Describe the bug**
When opening the GUI using the `4dcamera_gui` command, the following error shows if pyqtgraph is newer than 0.12.2:
```
Traceback (most recent call last):
  File "C:\Users\alexl\Documents\Scripting\Git\4dcamera_gui\ncempy_4dgui\run_ncempy_4dgui.py", line 7, in <module>
    main()
  File "c:\users\alexl\documents\scripting\git\4dcamera_gui\ncempy_4dgui\__init__.py", line 433, in main
    fourD_view = fourD()
  File "c:\users\alexl\documents\scripting\git\4dcamera_gui\ncempy_4dgui\__init__.py", line 59, in __init__
    self.real_space_image_view = pg.ImageView(imageItem=self.real_space_image_item)
  File "C:\Users\alexl\Anaconda3\envs\4dcamera_gui\lib\site-packages\pyqtgraph\imageview\ImageView.py", line 169, in __init__
    self.setImage(imageItem.image, autoRange=False, autoLevels=False, transform=imageItem.transform())
  File "C:\Users\alexl\Anaconda3\envs\4dcamera_gui\lib\site-packages\pyqtgraph\imageview\ImageView.py", line 279, in setImage
    raise TypeError("Image must be NumPy array or any object "
TypeError: Image must be NumPy array or any object that provides compatible attributes/methods:
  ['dtype', 'max', 'min', 'ndim', 'shape', 'size']
```

It seems that the stable version that gets installed in a new environment if you run `pip install pyqtgraph` is 0.12.4, which does not work with the GUI. I `pip install -e .` in a different (older) environment with pyqtgraph 0.11.0 and it works as expected. I tested this behavior and it seems to fail starting with pyqtgraph 0.12.3.

**To Reproduce**
- install/update pyqtgraph to a version >0.12.2
- `pip install -e .`
- `4dcamera_gui`

**Expected behavior**
GUI should open with prompt to input sparse data

**Desktop (please complete the following information):**
- OS: Windows 10

**Comment by ercius** [comment]
Thanks for reporting. Ill look into it. I see that I was developing with 0.11 so there must have been a breaking change in 0.12. Ill pi 0.11 for now to this and look into the issue next.

**Comment by ercius** [comment]
I have pinned pyqtgraph to 0.11 and also added PyQt5 as a requirement. These should work best on python 3.9. See fb27121dcb48d668b27d17f2b98bc974177d6fcf and d5e79352d23c8eed296fda18507badb9229a86c7
